runtime: nodejs18
instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'Up@123451'
  INSTANCE_CONNECTION_NAME: 'peak-elevator-463211-i3:asia-southeast1:upstairs-db'
  GCS_BUCKET_NAME: 'upstairs-bucket-v2'
  GCS_BASE_PATH: ''

beta_settings:
  cloud_sql_instances: 'peak-elevator-463211-i3:asia-southeast1:upstairs-db'