runtime: nodejs18
instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'Up@123451'
  INSTANCE_CONNECTION_NAME: 'calcium-ember-452706-a9:asia-southeast1:upstairssgn-db'
  GCS_BUCKET_NAME: 'upstairssgn-bucket'
  GCS_BASE_PATH: ''

beta_settings:
  cloud_sql_instances: 'calcium-ember-452706-a9:asia-southeast1:upstairssgn-db'